# Generated by Django 5.0.3 on 2024-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_image_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_upload',
        ),
        migrations.AddField(
            model_name='room',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
